### ISSUE TITLE
Is <br/> really inserted at every newline?

### ISSUE THREAD

**Issue by jessaustin** [markuadoc/markua#1]
I'm reading the Markua docs at https://leanpub.com/markua/read and it appears as though `<br/>` is inserted in the output for every newline in the input? This would be a terrible behavior. Most books and webpages are not limited to a 79-character line width. In fact there is no relation between line widths on input and line widths of desired output. It seems this is something envisioned for "poetry" which doesn't really consider the needs of prose.

**Comment by markuadoc** [comment]
Hi Jesse,

The idea is that most modern text editors automatically wrap lines, so
there's no need to add a newline unless you're explicitly trying to create
a newline -- like, say, in poetry.

By the way, if you're looking at Markua as a Leanpub author, note that we
haven't made Markua go live on Leanpub yet.  It's still only Leanpub
Flavoured Markdown, as described here:

https://leanpub.com/help/manual

When we add our Markua support to Leanpub we'll also keep the Leanpub
Flavoured Markdown support for a long time.

Thanks
Peter

**Comment by jessaustin** [comment]
I'm sorry, you're right. I've actually tried writing prose (as opposed to code) with wrap turned on now, and it's fine. I was assuming a false equivalence with html. Carry on! :smile:

**Comment by peterarmstrong** [comment]
Yeah, it's a bit of a mental switch to flip to go from "this is a format to
produce HTML" to "this is a format for writing books, and HTML is just one
output format" -- it took me years of Leanpub Flavoured Markdown to
actually figure out what the goals of Markua had to be, and even then I got
some major decisions wrong initially :)

Thanks very much for the feedback!  I really appreciate it, seriously :)
