### ISSUE TITLE
How to do line break?

### ISSUE THREAD

**Issue by nebrass** [markuadoc/markua#10]
Hello,

I am writing my first book using markua, and I wish to know how to insert a line break?
I tried `<br/>`, `<br />`, `\` but without success..
Please help me..

Nebrass

**Comment by peterarmstrong** [comment]
Hi,

Just a newline should work. If you're using Leanpub, the right thing to do is ask on the author forum at https://community.leanpub.com/c/authors or email hello@leanpub.com.

Thanks,
Peter
