### ISSUE TITLE
Missing Modularization?

### ISSUE THREAD

**Issue by tomschr** [markuadoc/markua#13]
## Problem

(sorry, it's me again :wink: )
Probably I'm blind, but I'm missing a chapter/section about how modularization is done in Markua.

I've searched the [Markua Specification](https://leanpub.com/markua/read) for the words "module", "include" etc. but couldn't find some. Also the TOC does not reveal this secret. :wink: 

## Use Case/Expected Behaviour

Documents like books, articles etc. consists usually of lots of chapters and sections. As such, it is hardly usable to write all your text in one single file. 

Therefor, add a new topic about how to split your document into several pieces and how you refer to these pieces in your main file.

**Comment by peterarmstrong** [comment]
This was deliberately omitted: Leanpub uses an approach in which there is a file called `Book.txt`, which is a list of files. However, I did not want to force this approach on everyone building a Markua processor. Now, that may have been a mistake, but it's the current decision.

Here's the relevant text from the spec, btw :)

"In LFM, we used Book.txt to define the book content. In Markua, the way that the list of manuscript files is defined is considered out of scope of the Markua specification itself. (Leanpub still uses the Book.txt approach to specify which files are in a book, but other Markua Processors could use other approaches.)"
