### ISSUE TITLE
Hyphen, En Dash and Em Dash

### ISSUE THREAD

**Issue by WalkerCodeRanger** [markuadoc/markua#5]
I notice that `--` is converted to an em dash on markuapad.com, but the spec doesn't mention that.  Also, how do we generate an en dash as opposed to a hyphen?  I know Markua is UTF-8 so it is possible to use the proper Unicode characters, but that seems to move away from the idea of a plaintext format and makes it hard to proof read for proper dash usage.

P.S. the spec also doesn't mention the conversion of `...`

**Comment by markuadoc** [comment]
I need to update the spec to specify that -- makes an em dash.  In terms of
producing an en dash, this is a niche-enough request that the Markua way
will be to use the proper Unicode characters.

**Comment by peterarmstrong** [comment]
This is resolved now in the latest versions of the Markua spec. For MarkuaPad issues, please file them here: https://github.com/bradens/markuapad
