### ISSUE TITLE
Open-source program to convert markua to the common publishing formats?

### ISSUE THREAD

**Issue by calebmadrigal** [markuadoc/markua#8]
Is there an open-source program to convert from markua to the common publishing formats?

**Comment by calebmadrigal** [comment]
Nvm, found it: https://github.com/markuadoc/markua-js

**Comment by peterarmstrong** [comment]
Hi,

Currently no, sorry.  Hopefully in future someone will add a Pandoc reader
and writer for Markua.  If you want to use an open source toolchain with
Markua (or with Leanpub Flavoured Markdown), then sticking to the subset of
either of them which is almost identical to standard Markdown (as defined
by John Gruber) is a good start.  This way, you can just treat your
document as Markdown, and Pandoc or Kramdown will work better, etc.

Thanks,
Peter

**Comment by peterarmstrong** [comment]
You won't have a good time using that -- it's extremely incomplete and
outdated.  We should arguably just unpublish it...

**Comment by markuadoc** [comment]
(Specifically, you'd be *way* better off using Kramdown or Pandoc than
that...)
